### ISSUE TITLE
Is this compatible with incsearch.vim?

### ISSUE THREAD

**Issue by davidosomething** [gelguy/cmd2.vim#1]
https://github.com/haya14busa/incsearch.vim/blob/master/doc/incsearch.txt#L73

incsearch.vim highlights matches immediately as characters are typed in `/` mode

Is there a way to use both `<Plug>(Cmd2Suggest)` AND `<Plug>(incsearch-forward)`
e.g.
`map / <Plug>(incsearch-forward)<Plug>(Cmd2Suggest)`

+@haya14busa maybe need to implement <Plug>(incsearch-forward-nohl)

**Comment by gelguy** [comment]
Unfortunately, it does not since both plugins use different methods to override the default /-search.

I have been working on trying to port the features but have been unable to find a good usage pattern.  `<Tab>` feels like the most natural key to press in both cases.

**Comment by gelguy** [comment]
The `hlsearch` and `incsearch` features have been added in fc92f71deeea6ebfe0b2c88ed8d9274295244b62. 

By default, your `&hlsearch` and `&incsearch` settings will be used.

At the moment, I do not intend to port `incsearch.vim`'s forward and backward movements.

**Comment by davidosomething** [comment]
awesome, great work! :+1:

**Comment by alessandro-molari** [comment]
What's the current status of this issue?
Does cmd2 support `incsearch.vim` plugin?

**Comment by gelguy** [comment]
Unfortunately, no as both use different cmdline-mode emulators (incsearch.vim uses vital-over).

Some basic functionality is common, such as `&hlsearch` and `&incsearch`. But incsearch.vim's more advanced features will not be available.
