### ISSUE TITLE
Caret at the end of commandline

### ISSUE THREAD

**Issue by alessandro-molari** [gelguy/cmd2.vim#14]
There is a caret at the end of the commandline:

[![asciicast](https://asciinema.org/a/78pxhjtcg5bsh2wgzwi7balgn.png)](https://asciinema.org/a/78pxhjtcg5bsh2wgzwi7balgn)

Obviously only a caret should be shown.

I'm using NeoVim.

**Comment by gelguy** [comment]
Unfortunately, this is a Neovim issue as Neovim does not respect the `t_ve` terminal escape code.

https://github.com/neovim/neovim/issues/3688

Other cmdline-mode simulators have the same issue.
