### ISSUE TITLE
Mapping help

### ISSUE THREAD

**Issue by toddbranch** [gelguy/cmd2.vim#15]
Using the suggested mappings, when I type '/', it opens search and puts '<F12>' as search input.  Have you seen this before?  If I actually type / then <F12> it works - but the mapping doesn't.  Spent a while trying to run it down and wasn't able to figure it out.

Thanks for your work on this plugin!

**Comment by gelguy** [comment]
Thanks for using!

Which terminal (or gVim/MacVim) and which OS would this be on?

The `<F-*>` function keys work differently on some terminals, so perhaps try changing `<F-12>` to some key combination that is unlikely to occur. Some `<C-*>` keys work differently on different terminals so do take that into account.

You might have a `cmap` to `<F-12>` which you can check using `:cmap <F-12>`.

 Just to confirm, what is your relevant `.vimrc` config and what is the sequence of events occuring?
