### ISSUE TITLE
Can't delete characters with backspace

### ISSUE THREAD

**Issue by alessandro-molari** [gelguy/cmd2.vim#4]
I start cmd2, type something and try to press Backspace, however the characters are not deleted.
Vim seems to ignore that hotkey.

**Comment by gelguy** [comment]
Can I ask for your OS and terminal (or gVim) for future troubleshooting?

I have noticed this occurring on slower terminals.

One solution I have found to work is 

``` vim
        \ 'loop_sleep': 0,
```

However, this makes Cmd2 not sleep (default 20ms) while waiting for input. This might consume more CPU than usual.

**Comment by alessandro-molari** [comment]
I'm using `rxvt-unicode` as terminal and `Gentoo` (`GNU/Linux`) as operating system.

**Comment by alessandro-molari** [comment]
It still doesn't work with that option, but I've noticed if I keep pressed backspace for 3/4 seconds, it will delete a single character; then I have to release the backspace and so on..

**Comment by gelguy** [comment]
Can you post a minmal .vimrc and steps to reproduce?

I am unable to use `rxvt-unicode`, and it currently works fine on Ubuntu tsch and Windows cmd.exe.

If this is a `rxvt-unicode` issue, I might not be able to fix it as I am unable to test or troubleshoot. Pull requests are welcome.

**Comment by alessandro-molari** [comment]
This is the relevant config:

``` VimL
" {{{ Options.

let g:Cmd2_cmd_mappings = {
      \ 'iw': {'command': 'iw', 'type': 'text', 'flags': 'Cpv'},
      \ 'ap': {'command': 'ap', 'type': 'line', 'flags': 'pv'},
      \ '^': {'command': '^', 'type': 'normal!', 'flags': 'r'},
      \ 'w': {'command': 'Cmd2#functions#Cword',
          \ 'type': 'function', 'flags': 'Cr'},
      \ }

let g:Cmd2_options = {
      \   '_complete_ignorecase': 1,
      \   '_complete_uniq_ignorecase': 0,
      \   '_quicksearch_ignorecase': 1,
      \   '_complete_start_pattern': '\<\(\k\+\(_\|\#\)\)\?',
      \   '_complete_fuzzy': 1,
      \   '_suggest_render': 'Cmd2#render#New().WithInsertCursor().WithAirlineMenu()',
      \   'loop_sleep': 0,
      \   'menu_hl': 'airline_x',
      \   'menu_selected_hl': 'airline_y',
      \   'menu_separator_hl': 'airline_x',
      \ }

" Character to type to start wildcard expansion in the command-line.
set wildcharm=<Tab>

" }}}

" {{{ Configure hotkeys.

" : or /: Enable Cmd2 automatically.
nmap : :<F11>
nmap / /<F11>

" <F11>: Enable Cmd2 manually.
cmap <F11> <Plug>(Cmd2Suggest)

" <Tab>: Perform completion using Cmd2.
cmap <expr> <Tab> Cmd2#ext#complete#InContext() ?
      \ '\<Plug>(Cmd2Complete)' :
      \ '\<Tab>'

" }}}
```

**Comment by gelguy** [comment]
I am unable to reproduce it on `tsch` or `cmd.exe`.

Does this issue occur under specific circumstances? e.g. large file, mutiple terminal sessions, long search string, etc.

I am trying to figure out where input keys can be dropped other than in `:sleep`.

**Comment by alessandro-molari** [comment]
Now it's working. I've changed nothing (i.e. `'loop_sleep': 0` fixed) but the problem is sometimes cmd2 isn't picking some configurations.

I mean, I've said that it didn't fix because in the first 5 / 6 tries it didn't work. Now it's working.

This is the same problem of #3 when I've said I had a white statusbar.. The problem gone away. Sometimes I still see the white bar and some times I cannot use backspace.

It seems those 2 options aren't picked sometimes.. It's strange..

Have you experienced something similar?

**Comment by gelguy** [comment]
Thanks for identifying the `sleep` issue.

Are you restarting vim each time you change the configurations? Cmd2 does not automatically update its variables when you change the `Cmd2_options` dictionary and source. The variable itself  `g:Cmd2_{variable}` has to be changed by itself.

A quick script I use to force the options to update

``` vim
  if exists('g:Cmd2_default_options')
    let s:options = extend(copy(g:Cmd2_default_options), g:Cmd2_options, 'force')
    for key in keys(s:options)
      if exists('g:Cmd2_' . key)
        unlet g:Cmd2_{key}
      endif
      let g:Cmd2_{key} = s:options[key]
    endfor
  endif
```

Place this after declaring the `g:Cmd2_options` dictionary.

**Comment by gelguy** [comment]
I have fixed the updating issue in d2aefaf6fc7addf627c302fed39b9b1bb2d735d0. Sourcing the settings now should update the variables.

The script above is no longer needed.

**Comment by alessandro-molari** [comment]
It seems to work now..

I will close the issue in a week (to be sure it's really fixed).

Thanks a lot for the awesome support :smile:

**Comment by gelguy** [comment]
I have done an update so the script can be reduced to

``` vim
  if exists('g:Cmd2_default_options')
    call Cmd2#init#Options(g:Cmd2_default_options)
  endif
```

Thanks for using the plugin!

**Comment by alessandro-molari** [comment]
It works correctly :) Thanks
