### ISSUE TITLE
Doesn't work with Paste Mode

### ISSUE THREAD

**Issue by alessandro-molari** [gelguy/cmd2.vim#5]
I have the following hotkeys configuration:

``` VimL
" : or /: Enable Cmd2 automatically.
nmap : :<F11>
nmap / /<F11>

" <F11>: Enable Cmd2 manually.
cmap <F11> <Plug>(Cmd2Suggest)

" <Tab>: Perform completion using Cmd2.
cmap <expr> <Tab> Cmd2#ext#complete#InContext() ?
      \ '\<Plug>(Cmd2Complete)' :
      \ '\<Tab>'
```

It normally works.

However, in Paste Mode when pressing `:` I get `:<F11>` in the commandline (without cmd2) instead of having an empty commandline with cmd2 active.

**Comment by gelguy** [comment]
This is vim's default behaviour. In `paste` mode, Command-line mode mappings are disabled.
See `:h paste`.

To disable Cmd2Suggest in `paste` mode, 

``` vim
nmap <expr> / '/' . (&paste ? '' : "\<Plug>(Cmd2Suggest)")
```

**Comment by alessandro-molari** [comment]
Thanks :+1:
